import {
  JobInterface,
  JobSubcriptionInterface,
} from "@/interfaces/job-interface";

export const jobConst = {
  category: [
    { id: 1, name: "Full-time" },
    { id: 2, name: "Part-time" },
    { id: 3, name: "Thực tập" },
    { id: 4, name: "Freelance" },
    { id: 5, name: "Thời vụ" },
    { id: 6, name: "Khác" },
  ],
  data: [
    {
      id: "1",
      title: "Lập trình viên Frontend",
      category: "Full-time",
      subscriptionId: "1",
      description: "Cần tìm lập trình viên Frontend có kinh nghiệm với React.",
      location: "Hà Nội",
      salary: 1500000,
      requirements: [
        "Kinh nghiệm ít nhất 2 năm với React",
        "Hiểu biết về HTML, CSS, JavaScript",
        "Có kinh nghiệm làm việc với RESTful APIs",
      ],
      startDate: new Date("2023-10-01"),
      workingHours: "Toàn thời gian",
      employerId: "1",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-15"),
      updatedAt: new Date("2023-09-20"),
    },
    {
      id: "2",
      title: "Nhân viên Marketing",
      category: "Part-time",
      subscriptionId: "2",
      description:
        "Tìm kiếm nhân viên Marketing có kinh nghiệm trong lĩnh vực digital marketing.",
      location: "Hồ Chí Minh",
      salary: 1200000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực marketing",
        "Hiểu biết về SEO, SEM, và Social Media Marketing",
        "Có khả năng phân tích dữ liệu và báo cáo",
      ],
      startDate: new Date("2023-10-05"),
      workingHours: "Bán thời gian",
      employerId: "2",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-18"),
      updatedAt: new Date("2023-09-22"),
    },
    {
      id: "3",
      title: "Kỹ sư phần mềm",
      category: "Full-time",
      subscriptionId: "3",
      description:
        "Cần tìm kỹ sư phần mềm có kinh nghiệm với Node.js và MongoDB.",
      location: "Đà Nẵng",
      salary: 2000000,
      requirements: [
        "Kinh nghiệm ít nhất 3 năm với Node.js",
        "Hiểu biết về MongoDB và các cơ sở dữ liệu NoSQL khác",
        "Có khả năng làm việc nhóm và giao tiếp tốt",
      ],
      startDate: new Date("2023-10-10"),
      workingHours: "Toàn thời gian",
      employerId: "3",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-20"),
      updatedAt: new Date("2023-09-25"),
    },
    {
      id: "4",
      title: "Thiết kế đồ họa",
      category: "Freelance",
      subscriptionId: "1",
      description:
        "Tìm kiếm designer có kinh nghiệm trong việc thiết kế đồ họa và UX/UI.",
      location: "Hà Nội",
      salary: 800000,
      requirements: [
        "Kinh nghiệm ít nhất 2 năm trong lĩnh vực thiết kế đồ họa",
        "Sử dụng thành thạo các công cụ thiết kế như Adobe Photoshop, Illustrator",
        "Có khả năng làm việc độc lập và quản lý thời gian tốt",
      ],
      startDate: new Date("2023-10-15"),
      workingHours: "Freelance",
      employerId: "4",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-22"),
      updatedAt: new Date("2023-09-27"),
    },
    {
      id: "5",
      title: "Quản lý dự án",
      category: "Full-time",
      subscriptionId: "2",
      description:
        "Cần tìm quản lý dự án có kinh nghiệm trong việc quản lý và điều phối các dự án công nghệ.",
      location: "Hồ Chí Minh",
      salary: 2500000,
      requirements: [
        "Kinh nghiệm ít nhất 5 năm trong lĩnh vực quản lý dự án",
        "Có chứng chỉ PMP hoặc tương đương",
        "Kỹ năng giao tiếp và lãnh đạo tốt",
      ],
      startDate: new Date("2023-10-20"),
      workingHours: "Toàn thời gian",
      employerId: "5",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-25"),
      updatedAt: new Date("2023-09-30"),
    },
    {
      id: "6",
      title: "Nhân viên bán hàng",
      category: "Part-time",
      subscriptionId: "3",
      description:
        "Tìm kiếm nhân viên bán hàng có kinh nghiệm trong lĩnh vực bán lẻ.",
      location: "Đà Nẵng",
      salary: 600000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực bán hàng",
        "Kỹ năng giao tiếp và thuyết phục tốt",
        "Có khả năng làm việc theo ca",
      ],
      startDate: new Date("2023-10-25"),
      workingHours: "Bán thời gian",
      employerId: "6",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-28"),
      updatedAt: new Date("2023-10-02"),
    },
    {
      id: "7",
      title: "Kỹ thuật viên IT",
      category: "Full-time",
      subscriptionId: "1",
      description:
        "Cần tìm kỹ thuật viên IT có kinh nghiệm trong việc bảo trì và sửa chữa máy tính.",
      location: "Hà Nội",
      salary: 900000,
      requirements: [
        "Kinh nghiệm ít nhất 2 năm trong lĩnh vực IT",
        "Có kiến thức về phần cứng và phần mềm máy tính",
        "Kỹ năng giải quyết vấn đề tốt",
      ],
      startDate: new Date("2023-10-30"),
      workingHours: "Toàn thời gian",
      employerId: "7",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-09-30"),
      updatedAt: new Date("2023-10-05"),
    },
    {
      id: "8",
      title: "Nhân viên kế toán",
      category: "Full-time",
      subscriptionId: "2",
      description:
        "Tìm kiếm nhân viên kế toán có kinh nghiệm trong việc quản lý sổ sách và báo cáo tài chính.",
      location: "Hồ Chí Minh",
      salary: 1100000,
      requirements: [
        "Kinh nghiệm ít nhất 3 năm trong lĩnh vực kế toán",
        "Có chứng chỉ kế toán hoặc tương đương",
        "Kỹ năng phân tích và báo cáo tốt",
      ],
      startDate: new Date("2023-11-01"),
      workingHours: "Toàn thời gian",
      employerId: "8",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-02"),
      updatedAt: new Date("2023-10-07"),
    },
    {
      id: "9",
      title: "Nhân viên chăm sóc khách hàng",
      category: "Part-time",
      subscriptionId: "3",
      description:
        "Cần tìm nhân viên chăm sóc khách hàng có kinh nghiệm trong việc giải quyết khiếu nại và hỗ trợ khách hàng.",
      location: "Đà Nẵng",
      salary: 700000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực chăm sóc khách hàng",
        "Kỹ năng giao tiếp và giải quyết vấn đề tốt",
        "Có khả năng làm việc theo ca",
      ],
      startDate: new Date("2023-11-05"),
      workingHours: "Bán thời gian",
      employerId: "9",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-05"),
      updatedAt: new Date("2023-10-10"),
    },
    {
      id: "10",
      title: "Nhân viên hành chính",
      category: "Full-time",
      subscriptionId: "1",
      description:
        "Tìm kiếm nhân viên hành chính có kinh nghiệm trong việc quản lý văn phòng và hỗ trợ các bộ phận khác.",
      location: "Hà Nội",
      salary: 950000,
      requirements: [
        "Kinh nghiệm ít nhất 2 năm trong lĩnh vực hành chính",
        "Kỹ năng tổ chức và quản lý thời gian tốt",
        "Có khả năng làm việc độc lập và theo nhóm",
      ],
      startDate: new Date("2023-11-10"),
      workingHours: "Toàn thời gian",
      employerId: "10",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-07"),
      updatedAt: new Date("2023-10-12"),
    },
    {
      id: "11",
      title: "Nhân viên kỹ thuật",
      category: "Freelance",
      subscriptionId: "2",
      description:
        "Cần tìm nhân viên kỹ thuật có kinh nghiệm trong việc lắp đặt và bảo trì thiết bị.",
      location: "Hồ Chí Minh",
      salary: 850000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực kỹ thuật",
        "Có kiến thức về các thiết bị điện tử và cơ khí",
        "Kỹ năng giải quyết vấn đề tốt",
      ],
      startDate: new Date("2023-11-15"),
      workingHours: "Freelance",
      employerId: "11",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-10"),
      updatedAt: new Date("2023-10-15"),
    },{
      id: "12",
      title: "Nhân viên bảo trì",
      category: "Part-time",
      subscriptionId: "3",
      description:
        "Tìm kiếm nhân viên bảo trì có kinh nghiệm trong việc bảo trì và sửa chữa thiết bị.",
      location: "Đà Nẵng",
      salary: 700000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực bảo trì",
        "Có kiến thức về các thiết bị cơ khí và điện tử",
        "Kỹ năng giải quyết vấn đề tốt",
      ],
      startDate: new Date("2023-11-20"),
      workingHours: "Bán thời gian",
      employerId: "12",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-12"),
      updatedAt: new Date("2023-10-17"),
    },
    {
      id: "13",
      title: "Nhân viên giao hàng",
      category: "Freelance",
      subscriptionId: "1",
      description:
        "Cần tìm nhân viên giao hàng có kinh nghiệm trong việc giao hàng và quản lý đơn hàng.",
      location: "Hà Nội",
      salary: 600000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực giao hàng",
        "Có phương tiện di chuyển (xe máy, xe đạp, v.v.)",
        "Kỹ năng giao tiếp và quản lý thời gian tốt",
      ],
      startDate: new Date("2023-11-25"),
      workingHours: "Freelance",
      employerId: "13",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-15"),
      updatedAt: new Date("2023-10-20"),
      
    },{
      id: "14",
      title: "Nhân viên bảo vệ",
      category: "Part-time",
      subscriptionId: "2",
      description:
        "Tìm kiếm nhân viên bảo vệ có kinh nghiệm trong việc bảo vệ an ninh và trật tự.",
      location: "Hồ Chí Minh",
      salary: 500000,
      requirements: [
        "Kinh nghiệm ít nhất 1 năm trong lĩnh vực bảo vệ",
        "Có khả năng làm việc theo ca",
        "Kỹ năng giao tiếp và quan sát tốt",
      ],
      startDate: new Date("2023-12-01"),
      workingHours: "Bán thời gian",
      employerId: "14",
      imageUrl:
        "https://images.ctfassets.net/7qqwgjna58ct/3WEd2JUHd2kdYfY34FanGj/ec7084674c3fd7420911240de5a9c5d7/get-a-job-with-no-experience.png",
      status: "Active",
      createdAt: new Date("2023-10-20"),
      updatedAt: new Date("2023-10-25"),
    }
  ] as JobInterface[],
  subscriptions: [
    {
      id: "1",
      name: "Basic",
      price: 1000000,
      duration: 30,
      descriptions: "HHHa.wwfs.sdsdj",
    },
    {
      id: "2",
      name: "Standard",
      price: 2000000,
      duration: 60,
      descriptions: "adsd.sdsdsd.sdsdsd",
    },
    {
      id: "3",
      name: "Premium",
      price: 3000000,
      duration: 90,
      descriptions: "asdnadn.asdsad.asdasd",
    },
  ] as JobSubcriptionInterface[],
};
