'use client"';
import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import ScrollToTopButton from "@/components/ui/button-scroll-to-top";
import dynamic from "next/dynamic";

const TopProgressBar = dynamic(
  () => import("@/components/ui/top-progress-bar")
);

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Header />
        <TopProgressBar />
        {children}
        <ScrollToTopButton />
      </body>
    </html>
  );
}
