import type { Metadata } from "next";
import { Be_Vietnam_Pro } from "next/font/google";
import "./globals.css";
import Header from "@/components/ui/header";
import ScrollToTopButton from "@/components/ui/button-scroll-to-top";
import dynamic from "next/dynamic";
import Footer from "@/components/ui/footer";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { Toaster } from "@/components/ui/sonner";
import { QueryClientWrapper } from "@/components/provider/query-client-provider";

const TopProgressBar = dynamic(
  () => import("@/components/ui/top-progress-bar")
);

const beVietNam = Be_Vietnam_Pro({
  variable: "--font-be-vietnam-pro",
  subsets: ["latin"],
  display: "swap",
  weight: "400",
});

export const metadata: Metadata = {
  title: "SWork - Nền tảng tuyển dụng thông minh",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body
        className={`${beVietNam.className} antialiased font-sans bg-white dark:bg-gray-950 text-gray-950 dark:text-zinc-50`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <QueryClientWrapper>
            <Header />
            <TopProgressBar />
            {children}
            <Toaster />
            <ScrollToTopButton />
            <Footer />
          </QueryClientWrapper>
        </ThemeProvider>
      </body>
    </html>
  );
}
